version: '3.7'
services:
  app:
    image: ghcr.io/yanislav-igonin/nbsp-bot/nbsp-bot:latest
    # networks:
    #   - web
    container_name: nbsp-bot
    environment: 
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - IS_WEBHOOK_DISABLED=true
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.docker.network: "web"

        traefik.http.services.nbsp-bot.loadbalancer.server.port: ${WEBHOOK_PORT}

        traefik.http.routers.nbsp-bot-secure.entrypoints: "https"
        traefik.http.routers.nbsp-bot-secure.rule: "Host(`${WEBHOOK_HOST}`) && PathPrefix(`${WEBHOOK_PATH}`)"
        traefik.http.routers.nbsp-bot-secure.tls: "true"
        traefik.http.routers.nbsp-bot-secure.service: "nbsp-bot"

# networks:
#   web:
#     driver: overlay
#     external: true
